"""
Caption suggestions, generated by Claude from the image itself plus the
artist's own past captions.

Design constraints, matching the rest of the product:
  * Captions are a creative starting point, never a performance claim.
    The model is instructed not to promise reach or ask for engagement.
  * The artist's voice comes from their own strongest past captions, so
    suggestions read like them rather than like generic marketing copy.
  * The feature degrades cleanly when ANTHROPIC_API_KEY is unset -- the
    endpoint returns a clear "not configured" error rather than failing
    at import time or crashing the request.
"""
from __future__ import annotations

import base64
import io
import logging
from dataclasses import dataclass

import anthropic
from PIL import Image
from pydantic import BaseModel, Field

from app.core.config import settings

logger = logging.getLogger(__name__)

# Claude processes images most cost-effectively at ~1568px on the long
# edge; anything larger is downscaled server-side anyway, so shrinking
# first saves upload time and tokens for no quality loss.
MAX_IMAGE_EDGE = 1200

# Captions are short by design, so a small ceiling is deliberate here
# rather than the usual larger default.
MAX_TOKENS = 2000

# How many of the artist's past captions to show as voice reference.
VOICE_SAMPLE_SIZE = 8

SYSTEM_PROMPT = """You write Instagram caption options for visual artists and photographers.

You will be given an image, its measured visual properties, and a sample of the \
artist's own past captions. Write caption options that sound like THIS artist -- \
match their length, punctuation, warmth or dryness, and whether they talk about \
process, materials, or nothing at all. If their captions are terse, yours are terse.

Rules:
- Never promise or imply reach, likes, or follower growth.
- No engagement bait: no "double tap if", no "comment below", no "save this".
- No hashtag walls. Suggest at most two or three hashtags, and only if the \
artist's own captions use them.
- Do not describe the image back to the viewer in flat literal terms; they can \
see it. Say something worth reading.
- Do not invent facts about the work -- its title, medium, location, or story. \
If you refer to the making of it, keep it to what the image plainly shows.
- Vary the options meaningfully: they should be different approaches, not \
three rewordings of one idea."""


class CaptionOption(BaseModel):
    text: str = Field(description="The caption itself, ready to post.")
    approach: str = Field(
        description="Two to four words naming the angle, e.g. 'process note' or 'quiet observation'."
    )


class CaptionSuggestions(BaseModel):
    options: list[CaptionOption] = Field(description="Three distinct caption options.")


class CaptionsNotConfiguredError(RuntimeError):
    """Raised when caption generation is used without an Anthropic API key."""


@dataclass
class CaptionContext:
    """Everything the model sees besides the image itself."""
    image_path: str
    brightness: float | None = None
    contrast: float | None = None
    dominant_colors: list[str] | None = None
    face_count: int = 0
    past_captions: list[str] | None = None


def _encode_image(path: str) -> tuple[str, str]:
    """Downscale and JPEG-encode an image for the API. Returns (media_type, base64)."""
    with Image.open(path) as im:
        im = im.convert("RGB")
        if max(im.size) > MAX_IMAGE_EDGE:
            im.thumbnail((MAX_IMAGE_EDGE, MAX_IMAGE_EDGE))
        buffer = io.BytesIO()
        im.save(buffer, format="JPEG", quality=85)
    return "image/jpeg", base64.standard_b64encode(buffer.getvalue()).decode("utf-8")


def _build_user_content(context: CaptionContext) -> list[dict]:
    media_type, encoded = _encode_image(context.image_path)

    details: list[str] = []
    if context.brightness is not None:
        tone = "dark" if context.brightness < 80 else "bright" if context.brightness > 180 else "mid-toned"
        details.append(f"Overall tone: {tone}.")
    if context.dominant_colors:
        details.append(f"Dominant colors: {', '.join(context.dominant_colors[:4])}.")
    if context.face_count:
        details.append(f"{context.face_count} face(s) detected.")

    if context.past_captions:
        sample = "\n".join(f"- {c}" for c in context.past_captions[:VOICE_SAMPLE_SIZE])
        voice = f"\n\nThe artist's own past captions, for voice reference:\n{sample}"
    else:
        voice = (
            "\n\nNo past captions are available for this account, so infer a "
            "restrained, artist-appropriate voice rather than imitating one."
        )

    prompt = (
        "Write three caption options for this image."
        + (f"\n\nMeasured properties: {' '.join(details)}" if details else "")
        + voice
    )

    return [
        {"type": "image", "source": {"type": "base64", "media_type": media_type, "data": encoded}},
        {"type": "text", "text": prompt},
    ]


def generate_captions(context: CaptionContext) -> list[CaptionOption]:
    """
    Generate caption options for an image. Raises CaptionsNotConfiguredError
    when no API key is configured, and lets anthropic.APIError subclasses
    propagate for the route to translate.
    """
    if not settings.ANTHROPIC_API_KEY:
        raise CaptionsNotConfiguredError(
            "Caption generation is not configured. Set ANTHROPIC_API_KEY to enable it."
        )

    client = anthropic.Anthropic(api_key=settings.ANTHROPIC_API_KEY)

    response = client.messages.parse(
        model=settings.CAPTION_MODEL,
        max_tokens=MAX_TOKENS,
        system=SYSTEM_PROMPT,
        messages=[{"role": "user", "content": _build_user_content(context)}],
        output_format=CaptionSuggestions,
    )

    if response.stop_reason == "refusal":
        logger.warning("Caption generation refused: %s", getattr(response.stop_details, "category", None))
        raise CaptionsNotConfiguredError(
            "The model declined to write captions for this image. Try a different image."
        )

    parsed = response.parsed_output
    return parsed.options if parsed else []
