"""add audience demographics to account

Revision ID: 199fd6f45144
Revises: 6fbd4ca67aa5
Create Date: 2026-08-20 10:41:29.323915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '199fd6f45144'
down_revision: Union[str, None] = '6fbd4ca67aa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default is required: existing rows have no value, so a bare
    # NOT NULL column cannot be added to a populated table.
    op.add_column(
        'instagram_accounts',
        sa.Column(
            'audience_countries',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
    )
    op.add_column('instagram_accounts', sa.Column('demographics_synced_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instagram_accounts', 'demographics_synced_at')
    op.drop_column('instagram_accounts', 'audience_countries')
    # ### end Alembic commands ###
