"""add views metric for Meta API impressions deprecation

Revision ID: 5389b9461516
Revises: a9ed3d4627c6
Create Date: 2026-08-19 23:14:20.156427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5389b9461516'
down_revision: Union[str, None] = 'a9ed3d4627c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instagram_post_metrics', sa.Column('views', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instagram_post_metrics', 'views')
    # ### end Alembic commands ###
