"""add caption approach column

Revision ID: 6fbd4ca67aa5
Revises: 5389b9461516
Create Date: 2026-08-20 00:16:31.850219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fbd4ca67aa5'
down_revision: Union[str, None] = '5389b9461516'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_captions', sa.Column('approach', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generated_captions', 'approach')
    # ### end Alembic commands ###
